#!/bin/sh

LOG=".allzip.log"

##################
function if_error
##################
{
if [[ $? -ne 0 ]]; then # check return code passed to function
print "$1 TIME:$TIME" | tee -a $LOG # if rc > 0 then print error msg and quit
exit $?
fi
}


FILES="*"

chflags -R nouchg $FILES
if_error "unlock failed"

for F in $FILES
do
    CWD=`pwd`
    ZIP="$F.zip"
    echo "ZIP: $CWD/$ZIP"
    if [ -f "$ZIP" ]
    then
        echo "'$ZIP' exists"
    elif [ -d "$F" ]
    then
        echo "ditto -c -k --sequesterRsrc --keepParent '$F/' '.$F.zip'"
        ditto -c -k --sequesterRsrc --keepParent "$F/" ".$F.zip"
        if_error "creating zip $F.zip failed"
        echo "mv '.$F.zip' '$F.zip'"
        mv ".$F.zip" "$F.zip"
        if_error "creating zip $F.zip failed"
        echo "rm -rf '$F'"
        rm -rf "$F/"
        if_error "remove $F/ failed"
    fi
done
